### ISSUE TITLE
Hacktoberfest - do what you want

### ISSUE THREAD

**Issue by lucas-carl** [lucas-carl/mockingbird#3]
I made this framework some time ago. Would like to revive it again.
Hope you have some helpful contributions. Do what you want!

**Comment by Aayushdh99** [comment]
I will take this task.

**Comment by lucas-carl** [comment]
@Aayushdh99, Great! Ask me if you have any questions

**Comment by Nienormalny** [comment]
Hi, how can i help you? I need to do some mr for hacktoberfest. So let me know what i should to do in frontend :)

**Comment by amarjeet045** [comment]
hello, I want to contribute in this kindly guide me thank you

**Comment by lucas-carl** [comment]
Hey guys, thanks for your interest in contributing!
I actually don't know what to do with this project. So, the idea was, that you can play around with the code and add some things, you think, could be helpful, or features that you yourself want to see in a CSS framework.
Just play around with the code. All contributions are helpful
